# Generated by Django 3.2.24 on 2024-02-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_alter_vendor_owner'),
        ('product', '0190_merge_20231221_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='vendor.vendor'),
        ),
    ]
